--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PMVirion/BossBarAPI
build-by-default: true
branches:
- main
projects:
  BossBarAPI:
    path: ""
    model: virion
    type: library
...
